### PR TITLE
[PROPOSAL] Framework for unit testing Jenkins pipelines

### PR DESCRIPTION
**Pull request by v1v**
This is the proposal to use UTs based on https://github.com/jenkinsci/JenkinsPipelineUnit

## Highlights
- Some simple test cases for some simple methods.
- Some more sophisticated test cases for validating the `validateDockerFileRubyVersion` and `shellcheck` methods.
- Jenkinsfile to validate those UTs
- Maven wrap the build process

### CODE REVIEW

**Comment by v1v** [comment]
@thomasleese @AlanGabbianelli @bevanloon as It seems you are one of the active users in this repo, may I ask you for feedback?

**Comment by bevanloon** [comment]
@v1v thanks for opening this. Sorry it's taken so long to get some eyes on it, we've had a busy few weeks. 

I've given it a little attention to kick off our CI on your commit. Unfortunately it's failing at the moment. We will try and put some time aside to investigate a bit further.

**Comment by bevanloon** [comment]
I've added a trello card to spend some time looking at this https://trello.com/c/5AIxylgN/1168-look-into-testing-govuk-jenkinslib

**Comment by v1v** [comment]
Any feedback?

**Comment by thomasleese** [comment]
Thanks for your PR, and spending the time to think about how we can test our Jenkins library. Sorry it’s taken so long to get a definitive answer from us.

After some discussion we’ve decided, unfortunately, that we don’t think it’s best to merge in this PR. Within GOV.UK we don’t have good knowledge of Groovy and maintaining these extra tests would be something we don’t have time to do, especially for a part of our system that we change so infrequently. We’d also need to spend some time to get it passing in our current configuration, our CI is erroring with the following logs:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 31: Method calls on objects not allowed outside "script" blocks. @ line 31, column 13.
               govuk.pipelineTest()
               ^

WorkflowScript: 30: Unknown stage section "error". Starting with version 0.5, steps in a stage must be in a ‘steps’ block. @ line 30, column 9.
           stage('Pipeline Test') {
           ^

WorkflowScript: 30: Expected one of "steps", "stages", or "parallel" for stage "Pipeline Test" @ line 30, column 9.
           stage('Pipeline Test') {
           ^

WorkflowScript: 7: Tool type "maven" does not have an install of "mvn" configured - did you mean "null"? @ line 7, column 15.
           maven 'mvn'
                 ^

WorkflowScript: 8: Tool type "jdk" does not have an install of "jdk8" configured - did you mean "null"? @ line 8, column 13.
           jdk 'jdk8'
               ^
```

Aside from this, as an organisation, we’re in the process of moving more towards using Concourse for our CI so there’s not much appetite for improving our Jenkins pipeline.

**Pull request closed without merging**
