### PR TITLE
Implement default branch detection

### PR DESCRIPTION
**Pull request by barrucadu**
Based on #84

### CODE REVIEW

**Comment by barrucadu** [comment]
[maslow](https://ci.integration.publishing.service.gov.uk/job/maslow/job/msw%252Fdefault-branch/1/console):

```
===
Output for testing: default branch is main
===
```

[collections](https://ci.integration.publishing.service.gov.uk/job/collections/job/msw%252Fdefault-branch/1/console):

```
===
Output for testing: default branch is master
===
```

**Comment by kevindew** [comment]
@barrucadu thank you, this looks great 👍  I think the main branch up-to-date with master risk is acceptable - I guess it may also actually do nothing if they are in line as I think all the branch related actions would only rely to head commitish.

That last sentence did have me ponder for a moment, do we actually need to know the branch name could we adjust the script to just work based on the headCommitish?

Aside from that left field thought (that may well have a fatal flaw) this is looking great and I'm happy for it to be merged in.

**Comment by barrucadu** [comment]
I think we'd at least need to know which branches are up-to-date with the default one, so we'd be able to change code like:

```
    stage("Checkout") {
      checkoutFromGitHubWithSSH(repoName, [shallow: env.BRANCH_NAME == defaultBranch])
    }
```

To:

```
    stage("Checkout") {
      checkoutFromGitHubWithSSH(repoName, [shallow: isBranchUpToDate(env.BRANCH_NAME)])
    }
```

Also `mergeIntoBranch` assumes it gets a branch name and not a commit hash, but that might be changeable:

```
def mergeIntoBranch(String branch) {
  if (isCurrentCommitOnBranch(branch)) {
    echo "Current commit is on ${branch}, so building this branch without " +
      "merging in ${branch} branch."
  } else {
    echo "Current commit is not on ${branch}, so attempting merge of ${branch} " +
      "branch before proceeding with build"

    sshagent(['govuk-ci-ssh-key']) {
      sh("git fetch --no-tags --depth=30 origin " +
         "+refs/heads/${branch}:refs/remotes/origin/${branch} " +
         "refs/heads/${env.BRANCH_NAME}:refs/remotes/origin/${env.BRANCH_NAME}")
    }
    sh("git merge --no-commit origin/${branch} || git merge --abort")
  }
}
```

**Comment by kevindew** [comment]
Ah yeah, that second scenario looks like it'd be a bit more confusing if we were communicating in terms of head rather than branch names.

The first one however seems like it might be better if it only did a shall of it was on the head. 

Ah well let's discard that whacky idea for now.

**Review by kevindew — APPROVED** [review]
Nice one thanks.

We'll merge into `default-branch` for now. I think this change was the last blocking thing before we'd be ready to merge default-branch in. I'll check that with @thomasleese who's overseeing bits.

**Comment by thomasleese** [comment]
This is great, thanks @barrucadu!

**Pull request merged**
